Update Italian localization
nicotine-plus/nicotine-plus pull request #1518
Opened 2021-09-02 09:11 UTC by M0Rf30

As in title,
Regards

2021-09-02 12:49 UTC, slook requested changes
- [ ] "Result _Filters" -> "_Result Filters" - see https://github.com/nicotine-plus/nicotine-plus/issues/1500#issuecomment-911158480 - THIS ISSUE NEEDS TO BE RE-OPENED (sorry my mistake) s.

- [ ] "Free _Slot" -> "Free Sl_ot" - see #1516 
 
- [ ] "Send _Message" -> "Send M_essage" - see #1515

- [ ] "Brow_se Files" -> "_Browse Files"

2021-09-02 12:49 UTC, slook commented on po/it.po
> +msgid "Result _Filters [%d]"
Key accelerator shortcut will be changed to "_Result Filters" see https://github.com/nicotine-plus/nicotine-plus/issues/1500#issuecomment-911158480 sorry. s.

2021-09-02 12:49 UTC, slook commented on po/it.po
>  msgid "Free _Slot"
Key accelerator shortcut will be changed to "Free Slo_t" see #1516

2021-09-04 03:34 UTC, mathiascode commented
@M0Rf30 Thank you. I haven't merged this yet due to several strings being refined in master at the moment, but this should hopefully be done soon.

2021-09-11 13:59 UTC, merged