Leech Detector: add fallback check for users with no shares
nicotine-plus/nicotine-plus pull request #2747
Opened 2023-11-09 22:03 UTC by mathiascode

Also remove redundant user stat request, since we're watching all queued users.

Fixes #1565

2023-11-09 22:09 UTC, mathiascode commented
Another thing we need to do for Nicotine+ 3.3.0 is to delay download queue requests on startup until the compressed share messages are ready. This should fix any remaining "no files shared" false positives Nicotine+ users with large shares might be experiencing.

2023-11-10 09:58 UTC, slook requested changes

2023-11-10 09:58 UTC, slook commented on pynicotine/plugins/leech_detector/__init__.py
> +            self.log("User %s has no shared files according to the server, verifying if this is true…", user)
"verifying" -> "requesting shares list to verify"

2023-11-10 09:58 UTC, slook commented on pynicotine/plugins/leech_detector/__init__.py
> +            self.probed_users[user] = "requesting_fallback"
`"requesting_fallback"` -> `"requesting_list"`

2023-11-10 09:58 UTC, slook commented on pynicotine/plugins/leech_detector/__init__.py
> +            self.probed_users[user] = "requesting"
`"requesting"` -> `"requesting_stats"`

2023-11-10 09:58 UTC, slook commented on pynicotine/plugins/leech_detector/__init__.py
> +        if self.probed_users[user] not in {"requesting", "requesting_fallback"}:
`if not self.probed_users[user].startswith("requesting"):`

2023-11-11 12:45 UTC, merged